services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "14268:14268" # Jaeger collector HTTP
      - "14269:14269" # Jaeger collector health check
      - "14250:14250" # Jaeger gRPC
